[tool.qpro]
[[tool.qpro.server_targets]]
user = ""
host = ""
path = ""
port = "22"

[tool.qpro.config]
build = ""
entry_point = "main.py"
executable = "python main.py"
input_file = "dist/input.txt"
template_root = "template/"
